// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nucleic/rollup/state.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StateStatus int32

const (
	StateStatus_PENDING   StateStatus = 0
	StateStatus_FINALIZED StateStatus = 1
	StateStatus_REVERTED  StateStatus = 3
)

var StateStatus_name = map[int32]string{
	0: "PENDING",
	1: "FINALIZED",
	3: "REVERTED",
}

var StateStatus_value = map[string]int32{
	"PENDING":   0,
	"FINALIZED": 1,
	"REVERTED":  3,
}

func (x StateStatus) String() string {
	return proto.EnumName(StateStatus_name, int32(x))
}

func (StateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_486e5873fc407807, []int{0}
}

// StateInfoIndex is the data used for indexing and retrieving a StateInfo
// it updated and saved with every UpdateState in StateInfo.
// We use the this structure also for:
// 1. LatestStateInfoIndex which defines the rollups' current (latest) index of the last UpdateState
// 2. LatestFinalizedStateIndex which defines the rollups' current (latest) index of the latest StateInfo that was finalized
type StateInfoIndex struct {
	// rollupId is the rollup that the sequencer belongs to and asking to update
	// it used to identify the what rollup a StateInfo belongs
	// The rollupId follows the same standard as cosmos chain_id
	RollupId string `protobuf:"bytes,1,opt,name=rollupId,proto3" json:"rollupId,omitempty"`
	// index is a sequential increasing number, updating on each
	// state update used for indexing to a specific state info, the first index is 1
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *StateInfoIndex) Reset()         { *m = StateInfoIndex{} }
func (m *StateInfoIndex) String() string { return proto.CompactTextString(m) }
func (*StateInfoIndex) ProtoMessage()    {}
func (*StateInfoIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_486e5873fc407807, []int{0}
}
func (m *StateInfoIndex) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateInfoIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StateInfoIndex.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StateInfoIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateInfoIndex.Merge(m, src)
}
func (m *StateInfoIndex) XXX_Size() int {
	return m.Size()
}
func (m *StateInfoIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_StateInfoIndex.DiscardUnknown(m)
}

var xxx_messageInfo_StateInfoIndex proto.InternalMessageInfo

func (m *StateInfoIndex) GetRollupId() string {
	if m != nil {
		return m.RollupId
	}
	return ""
}

func (m *StateInfoIndex) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

// StateInfo defines a state of the rollup.
type StateInfo struct {
	// stateInfoIndex defines what rollup the state belongs to
	// and in which index it can be referenced
	StateInfoIndex StateInfoIndex `protobuf:"bytes,1,opt,name=stateInfoIndex,proto3" json:"stateInfoIndex"`
	// sequencer is the bech32-encoded address of the sequencer sent the update
	Sequencer string `protobuf:"bytes,2,opt,name=sequencer,proto3" json:"sequencer,omitempty"`
	// startHeight is the block height of the first block in the batch
	StartHeight uint64 `protobuf:"varint,3,opt,name=startHeight,proto3" json:"startHeight,omitempty"`
	// numBlocks is the number of blocks included in this batch update
	NumBlocks uint64 `protobuf:"varint,4,opt,name=numBlocks,proto3" json:"numBlocks,omitempty"`
	// DAPath is the description of the location on the DA layer
	DAPath string `protobuf:"bytes,5,opt,name=DAPath,proto3" json:"DAPath,omitempty"`
	// version is the version of the rollup
	Version uint64 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	// creationHeight is the height at which the UpdateState took place
	CreationHeight uint64 `protobuf:"varint,7,opt,name=creationHeight,proto3" json:"creationHeight,omitempty"`
	// status is the status of the state update
	Status StateStatus `protobuf:"varint,8,opt,name=status,proto3,enum=nucleic.rollup.StateStatus" json:"status,omitempty"`
	// BDs is a list of block description objects (one per block)
	// the list must be ordered by height, starting from startHeight to startHeight+numBlocks-1
	BDs BlockDescriptors `protobuf:"bytes,9,opt,name=BDs,proto3" json:"BDs"`
}

func (m *StateInfo) Reset()         { *m = StateInfo{} }
func (m *StateInfo) String() string { return proto.CompactTextString(m) }
func (*StateInfo) ProtoMessage()    {}
func (*StateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_486e5873fc407807, []int{1}
}
func (m *StateInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StateInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateInfo.Merge(m, src)
}
func (m *StateInfo) XXX_Size() int {
	return m.Size()
}
func (m *StateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StateInfo proto.InternalMessageInfo

func (m *StateInfo) GetStateInfoIndex() StateInfoIndex {
	if m != nil {
		return m.StateInfoIndex
	}
	return StateInfoIndex{}
}

func (m *StateInfo) GetSequencer() string {
	if m != nil {
		return m.Sequencer
	}
	return ""
}

func (m *StateInfo) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *StateInfo) GetNumBlocks() uint64 {
	if m != nil {
		return m.NumBlocks
	}
	return 0
}

func (m *StateInfo) GetDAPath() string {
	if m != nil {
		return m.DAPath
	}
	return ""
}

func (m *StateInfo) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *StateInfo) GetCreationHeight() uint64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *StateInfo) GetStatus() StateStatus {
	if m != nil {
		return m.Status
	}
	return StateStatus_PENDING
}

func (m *StateInfo) GetBDs() BlockDescriptors {
	if m != nil {
		return m.BDs
	}
	return BlockDescriptors{}
}

func init() {
	proto.RegisterEnum("nucleic.rollup.StateStatus", StateStatus_name, StateStatus_value)
	proto.RegisterType((*StateInfoIndex)(nil), "nucleic.rollup.StateInfoIndex")
	proto.RegisterType((*StateInfo)(nil), "nucleic.rollup.StateInfo")
}

func init() { proto.RegisterFile("nucleic/rollup/state.proto", fileDescriptor_486e5873fc407807) }

var fileDescriptor_486e5873fc407807 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x8f, 0x69, 0xd7, 0x36, 0xaf, 0x10, 0x55, 0xd6, 0x84, 0xac, 0x82, 0x42, 0xb4, 0x03, 0xaa,
	0x90, 0x48, 0xc4, 0x76, 0x80, 0xeb, 0xa2, 0x04, 0x88, 0x98, 0xaa, 0x29, 0x43, 0x1c, 0x76, 0x4b,
	0x33, 0x93, 0x46, 0xcb, 0xec, 0x60, 0x3b, 0x30, 0x6e, 0x7c, 0x04, 0x3e, 0xd6, 0x8e, 0x3b, 0x72,
	0x42, 0xa8, 0xfd, 0x22, 0x28, 0x4e, 0xba, 0xb5, 0xd1, 0x6e, 0xfe, 0xbd, 0xdf, 0x9f, 0xf7, 0x9e,
	0xf5, 0x60, 0xca, 0xaa, 0xb4, 0xa0, 0x79, 0xea, 0x09, 0x5e, 0x14, 0x55, 0xe9, 0x49, 0x95, 0x28,
	0xea, 0x96, 0x82, 0x2b, 0x8e, 0xad, 0x96, 0x73, 0x1b, 0x6e, 0xba, 0x9f, 0xf1, 0x8c, 0x6b, 0xca,
	0xab, 0x5f, 0x8d, 0x6a, 0xda, 0x4d, 0x58, 0x14, 0x3c, 0xbd, 0x6c, 0xb8, 0x03, 0x1f, 0xac, 0xb3,
	0x3a, 0x30, 0x62, 0x5f, 0x79, 0xc4, 0x2e, 0xe8, 0x35, 0x9e, 0xc2, 0xa8, 0xd1, 0x45, 0x17, 0x04,
	0x39, 0x68, 0x66, 0xc6, 0x77, 0x18, 0xef, 0xc3, 0x5e, 0x5e, 0x8b, 0xc8, 0x23, 0x07, 0xcd, 0xfa,
	0x71, 0x03, 0x0e, 0x7e, 0xf5, 0xc0, 0xbc, 0x0b, 0xc1, 0x27, 0x60, 0xc9, 0x9d, 0x44, 0x9d, 0x32,
	0x3e, 0xb4, 0xdd, 0xdd, 0x61, 0xdd, 0xdd, 0xbe, 0x7e, 0xff, 0xe6, 0xef, 0x0b, 0x23, 0xee, 0x78,
	0xf1, 0x73, 0x30, 0x25, 0xfd, 0x56, 0x51, 0x96, 0x52, 0xa1, 0xbb, 0x9a, 0xf1, 0x7d, 0x01, 0x3b,
	0x30, 0x96, 0x2a, 0x11, 0xea, 0x23, 0xcd, 0xb3, 0xa5, 0x22, 0x3d, 0x3d, 0xd5, 0x76, 0xa9, 0xf6,
	0xb3, 0xea, 0xca, 0xaf, 0x37, 0x96, 0xa4, 0xaf, 0xf9, 0xfb, 0x02, 0x7e, 0x0a, 0x83, 0xe0, 0xf8,
	0x34, 0x51, 0x4b, 0xb2, 0xa7, 0xa3, 0x5b, 0x84, 0x09, 0x0c, 0xbf, 0x53, 0x21, 0x73, 0xce, 0xc8,
	0x40, 0x7b, 0x36, 0x10, 0xbf, 0x04, 0x2b, 0x15, 0x34, 0x51, 0x39, 0x67, 0x6d, 0xd3, 0xa1, 0x16,
	0x74, 0xaa, 0xf8, 0x08, 0x06, 0xf5, 0x26, 0x95, 0x24, 0x23, 0x07, 0xcd, 0xac, 0xc3, 0x67, 0x0f,
	0x6e, 0x7f, 0xa6, 0x25, 0x71, 0x2b, 0xc5, 0xef, 0xa0, 0xe7, 0x07, 0x92, 0x98, 0xfa, 0xbf, 0x9c,
	0xae, 0x43, 0xcf, 0x1c, 0x50, 0x99, 0x8a, 0xbc, 0x54, 0x5c, 0xc8, 0xf6, 0xc7, 0x6a, 0xcb, 0xab,
	0xb7, 0x30, 0xde, 0x0a, 0xc4, 0x63, 0x18, 0x9e, 0x86, 0xf3, 0x20, 0x9a, 0x7f, 0x98, 0x18, 0xf8,
	0x09, 0x98, 0xef, 0xa3, 0xf9, 0xf1, 0x49, 0x74, 0x1e, 0x06, 0x13, 0x84, 0x1f, 0xc3, 0x28, 0x0e,
	0xbf, 0x84, 0xf1, 0xe7, 0x30, 0x98, 0xf4, 0xfc, 0x4f, 0x37, 0x2b, 0x1b, 0xdd, 0xae, 0x6c, 0xf4,
	0x6f, 0x65, 0xa3, 0xdf, 0x6b, 0xdb, 0xb8, 0x5d, 0xdb, 0xc6, 0x9f, 0xb5, 0x6d, 0x9c, 0xbf, 0xc9,
	0x72, 0xb5, 0xac, 0x16, 0x6e, 0xca, 0xaf, 0xbc, 0x76, 0x92, 0xd7, 0x8c, 0xaa, 0x1f, 0x5c, 0x5c,
	0x6e, 0xb0, 0x77, 0xbd, 0x39, 0x29, 0xf5, 0xb3, 0xa4, 0x72, 0x31, 0xd0, 0x37, 0x75, 0xf4, 0x3f,
	0x00, 0x00, 0xff, 0xff, 0xe1, 0x1e, 0x4b, 0xa4, 0xb3, 0x02, 0x00, 0x00,
}

func (m *StateInfoIndex) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateInfoIndex) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateInfoIndex) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RollupId) > 0 {
		i -= len(m.RollupId)
		copy(dAtA[i:], m.RollupId)
		i = encodeVarintState(dAtA, i, uint64(len(m.RollupId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StateInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BDs.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.Status != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if m.CreationHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.Version != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x30
	}
	if len(m.DAPath) > 0 {
		i -= len(m.DAPath)
		copy(dAtA[i:], m.DAPath)
		i = encodeVarintState(dAtA, i, uint64(len(m.DAPath)))
		i--
		dAtA[i] = 0x2a
	}
	if m.NumBlocks != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.NumBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.StartHeight != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Sequencer) > 0 {
		i -= len(m.Sequencer)
		copy(dAtA[i:], m.Sequencer)
		i = encodeVarintState(dAtA, i, uint64(len(m.Sequencer)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.StateInfoIndex.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StateInfoIndex) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RollupId)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovState(uint64(m.Index))
	}
	return n
}

func (m *StateInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StateInfoIndex.Size()
	n += 1 + l + sovState(uint64(l))
	l = len(m.Sequencer)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.StartHeight != 0 {
		n += 1 + sovState(uint64(m.StartHeight))
	}
	if m.NumBlocks != 0 {
		n += 1 + sovState(uint64(m.NumBlocks))
	}
	l = len(m.DAPath)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovState(uint64(m.Version))
	}
	if m.CreationHeight != 0 {
		n += 1 + sovState(uint64(m.CreationHeight))
	}
	if m.Status != 0 {
		n += 1 + sovState(uint64(m.Status))
	}
	l = m.BDs.Size()
	n += 1 + l + sovState(uint64(l))
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StateInfoIndex) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateInfoIndex: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateInfoIndex: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollupId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollupId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StateInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateInfoIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StateInfoIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequencer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sequencer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumBlocks", wireType)
			}
			m.NumBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DAPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DAPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= StateStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BDs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BDs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
